---
driver:
  name: vagrant
  vm_hostname: myapm
  customize:
    memory: <%= ENV['APM_RAM'] %>
    cpus: <%= ENV['APM_CPU'] %>
    name: myapm
  network:
   - ['private_network', ip: '10.1.1.20']

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: mycsc-7.6

suites:
  - name: myapm
    run_list:
#      - recipe[ibm_apm::create_threshold]
#      - recipe[ibm_apm::get_thresholds]
#      - recipe[ibm_apm::get_token]
      - recipe[ibm_apm::preinstall_apm]
      - recipe[ibm_apm::install_apm]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
